micronaut:
  application:
    name: selection

  server:
    cors:
      enabled: true
    thread-selection: IO
    netty:
      access-logger:
        enabled: true
        log-format: common

jackson:
  serialization:
    FAIL_ON_UNKNOWN_PROPERTIES: false
    WRITE_DATES_AS_TIMESTAMPS: false
